### PR TITLE
add presentation video

### PR DESCRIPTION
**Pull request by mwiesen**
@brntbeer Hi. Just created a video from your presentation. You care to pull? Since your talks repo is public, I then can send links to the vid, if you don't mind.

### CODE REVIEW

**Comment by brntbeer** [comment]
@mwiesen would it be possible for you to add this file into LFS before submitting here?

Thanks for adding this!

**Comment by mwiesen** [comment]
@brntbeer I'd love to, but it has to wait for 2 weeks. Leaving for vacation...

**Comment by mwiesen** [comment]
@brntbeer should now be tracked with git lfs..

**Comment by mwiesen** [comment]
@brntbeer were you able to merge?

**Pull request closed without merging**
